package com.gd.oa;

import jodd.io.FileUtil;
import jodd.json.JsonArray;
import jodd.json.JsonObject;
import jodd.json.JsonParser;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;

import java.io.IOException;
import java.util.*;

public class FAQ {
    private static final Logger log = LoggerFactory.getLogger(FAQ.class);


    //Below code are generated by GsonFormat..

    /**
     * faqs : [{"name":"如何重置账户密码","phrase_match_return":"text","phrase_match_keywords":["账户密码"],"broad_match_keyords":["账户","密码"],"title":"如何重置账户密码","description":"需登录 GoDaddy 网站完成两步操作，之后我们将给您发送一封附链接的电子邮件以供您重置密码使用。","url":"https://www.gaoyongsheng.cn/faq/pages/howToResetAnAccountPassword.html","pic_url":"https://www.gaoyongsheng.cn/downloadbuild/images/faq_godaddy_logo.png","text":"您可以<a href='https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxbe9a77c9f3338cb9&redirect_uri=https%3a%2f%2fwww.gaoyongsheng.cn%2foa%2fredir%2faccount%3fpath%3dsecurity%253f&response_type=code&scope=snsapi_base&state=666#wechat_redirect'>点击这里<\/a>前往 GoDaddy 网站的密码重置页面 -> 填写用户名和密码 -> 提交\n\n您还可以点击<a href='#godaddy_more_url#'>查看更多<\/a>了解更多问题。"},{"name":"如何找回用户名","phrase_match_return":"news","phrase_match_keywords":["找回用户名","找回账号"],"broad_match_keyords":["账户","用户名"],"title":"如何找回用户名","description":"需登录 GoDaddy 网站完成两步操作，之后我们通过电子邮件向您发送您的客户编号。","url":"https://www.gaoyongsheng.cn/faq/pages/howToRetrieveAUserName.html","pic_url":"https://www.gaoyongsheng.cn/downloadbuild/images/faq_godaddy_logo.png","text":""},{"name":"如何开启两步验证","phrase_match_return":"news","phrase_match_keywords":["开启验证"],"broad_match_keyords":["验证","安全"],"title":"如何开启两步验证","description":"您可以通过开启两部验证来提高您账号的安全性。","url":"https://www.gaoyongsheng.cn/faq/pages/howDoITurnOnTwo-stepValidation.html","pic_url":"https://www.gaoyongsheng.cn/downloadbuild/images/faq_godaddy_logo.png","text":""},{"name":"如何关闭两步验证","phrase_match_return":"news","phrase_match_keywords":["关闭验证"],"broad_match_keyords":["验证","安全"],"title":"如何关闭两步验证","description":"关闭两部验证后，您的账号将不再要求两步验证。","url":"https://www.gaoyongsheng.cn/faq/pages/howDoITurnOffTwo-stepTalidation.html","pic_url":"https://www.gaoyongsheng.cn/downloadbuild/images/faq_godaddy_logo.png","text":""},{"name":"如何查看产品的有效期","phrase_match_return":"text","phrase_match_keywords":["产品有效期"],"broad_match_keyords":["有效期"],"title":"如何查看产品的有效期","description":"您可以通过两个平台来查看所有产品的购买记录：GoDaddy 微信公众号和官网。","url":"https://www.gaoyongsheng.cn/faq/pages/howToViewProductAvailability.html","pic_url":"https://www.gaoyongsheng.cn/downloadbuild/images/faq_godaddy_logo.png","text":"您可以<a href='http://www.qq.com' data-miniprogram-appid='wx03073c4b1d0c3cdd' data-miniprogram-path='pages/myaccount/myaccount?activeIndex=1'>点击这里<\/a>直接进入\u201c产品\u201d页面 -> 点击产品分类列表 -> 查看产品的有效期\n\n如未绑定需绑定 GoDaddy 账户,您还可以点击<a href='#godaddy_more_url#'>查看更多<\/a>了解更多问题。"},{"name":"如何查看历史订单","phrase_match_return":"text","phrase_match_keywords":["历史订单"],"broad_match_keyords":["订单","历史"],"title":"如何查看历史订单","description":"您可以通过两个平台查看历史订单：GoDaddy 微信公众号和官网。","url":"https://www.gaoyongsheng.cn/faq/pages/howToViewHistoricalOrders.html","pic_url":"https://www.gaoyongsheng.cn/downloadbuild/images/faq_godaddy_logo.png","text":"您可以<a href='http://www.qq.com' data-miniprogram-appid='wx03073c4b1d0c3cdd' data-miniprogram-path='pages/myaccount/myaccount?activeIndex=2'>点击这里<\/a>直接进入\u201c订单\u201d页面 -> 查看历史订单\n\n如未绑定需绑定 GoDaddy 账户,您还可以点击<a href='#godaddy_more_url#'>查看更多<\/a>了解更多问题。"},{"name":"是否提供增值税发票","phrase_match_return":"text","phrase_match_keywords":["发票","收据"],"broad_match_keyords":["发票","收据"],"title":"是否提供增值税发票","description":"很遗憾不能提供增值税发票，但可查看订单收据。","url":"https://www.gaoyongsheng.cn/faq/pages/whetherToProvideVATInvoice.html","pic_url":"https://www.gaoyongsheng.cn/downloadbuild/images/faq_godaddy_logo.png","text":"很遗憾不能提供增值税发票，但可查看订单收据。\n您可以<a href='http://www.qq.com' data-miniprogram-appid='wx03073c4b1d0c3cdd' data-miniprogram-path='pages/myaccount/myaccount?activeIndex=2'>点击这里<\/a>直接进入\u201c订单\u201d页面 -> 点击\u201c收据\u201d按钮 -> 查看收据\n\n如未绑定需绑定 GoDaddy 账户,您还可以点击<a href='#godaddy_more_url#'>查看更多<\/a>了解更多问题"},{"name":"如何取消产品自动续费","phrase_match_return":"text","phrase_match_keywords":["自动续费"],"broad_match_keyords":["续费"],"title":"如何取消产品自动续费","description":"取消产品自动续费，需要在 GoDaddy 网站进行四步操作。","url":"https://www.gaoyongsheng.cn/faq/pages/howToCancelAutomaticRenewal.html","pic_url":"https://www.gaoyongsheng.cn/downloadbuild/images/faq_godaddy_logo.png","text":"您可以<a href='http://www.qq.com' data-miniprogram-appid='wx03073c4b1d0c3cdd' data-miniprogram-path='pages/myaccount/myaccount?activeIndex=2'>点击这里<\/a>直接进入\u201c订单\u201d页面 -> 点击产品分类列表 -> 点击自动续费开关 -> 点击\u201c关闭自动\u201d\n\n 如未绑定需绑定 GoDaddy 账户,您还可以点击<a href='#godaddy_more_url#'>查看更多<\/a>了解更多方法。"},{"name":"如何变更域名联系人信息","phrase_match_return":"news","phrase_match_keywords":["域名联系人"],"broad_match_keyords":["域名","联系人"],"title":"如何变更域名联系人信息","description":"域名有四种联系人，您可以随时更改域名的联系人信息。","url":"https://www.gaoyongsheng.cn/faq/pages/howToChangeDomainNameContactInformation.html","pic_url":"https://www.gaoyongsheng.cn/downloadbuild/images/faq_godaddy_logo.png","text":""},{"name":"如何做域名账户变更","phrase_match_return":"news","phrase_match_keywords":["域名账户变更"],"broad_match_keyords":["域名","账户"],"title":"如何做域名账户变更","description":"如果需要将域名从我们这里的一个账户移动到另一个，则需要在被称为账户更该的正确位置开始，如果需要将域名移动到其他注册商，请参阅将域名转移至其他注册商。","url":"https://www.gaoyongsheng.cn/faq/pages/howToMakeDomainNameAccountChanges.html","pic_url":"https://www.gaoyongsheng.cn/downloadbuild/images/faq_godaddy_logo.png","text":""},{"name":"如何做域名解析","phrase_match_return":"news","phrase_match_keywords":["域名解析"],"broad_match_keyords":["域名","解析"],"title":"如何做域名解析","description":"做域名解析需要更改域名服务器，而更改域名服务器取决于域名注册地和网站注册地。","url":"https://www.gaoyongsheng.cn/faq/pages/howToDoDomainNameResolution.html","pic_url":"https://www.gaoyongsheng.cn/downloadbuild/images/faq_godaddy_logo.png","text":""},{"name":"如何做域名转入","phrase_match_return":"news","phrase_match_keywords":["域名转入"],"broad_match_keyords":["域名","转入"],"title":"如何做域名转入","description":"域名转入需要在当前的注册商处完成一些步骤， 并在 GoDaddy 处完成一些步骤。","url":"https://www.gaoyongsheng.cn/faq/pages/theDomainNameInto.html","pic_url":"https://www.gaoyongsheng.cn/downloadbuild/images/faq_godaddy_logo.png","text":""},{"name":"如何做域名转出","phrase_match_return":"news","phrase_match_keywords":["域名转出"],"broad_match_keyords":["域名","转出"],"title":"如何做域名转出","description":"域名转移至其他注册商的过程比较花时间，整个过程可能需要最多10天来完成。","url":"https://www.gaoyongsheng.cn/faq/pages/howDoDomainNameTransfer.html","pic_url":"https://www.gaoyongsheng.cn/downloadbuild/images/faq_godaddy_logo.png","text":""}]
     * combine_faq_each_template : <a href='#LINK#'>#TITLE#</a>
     * combine_faq_templates : GoDaddy很高兴为您服务，您可以通过点击以下链接来获取相关答案:
     * <p>
     * #FAQ_BODY#其他更多问题…(<a href='#godaddy_more_url#'>点击这里</a>)
     * nomatch_faq_templates : GoDaddy很高兴为您服务，您可以通过点击以下链接来获取相关答案:
     * <p>
     * #FAQ_BODY#其他更多问题…(<a href='#godaddy_more_url#'>点击这里</a>)
     * nomatch_faq_return : 5
     * godaddy_more_url : https://sg.godaddy.com/zh/help/search?q=#KEYWORD#&topic=&pg=1&path=
     * godaddy_more_url_default : https://www.gaoyongsheng.cn/faq/index.html
     * language : zh_CN
     */

    private String combine_faq_each_template;
    private String combine_faq_templates;
    private String nomatch_faq_templates;
    private int nomatch_faq_return;
    private String godaddy_more_url;
    private String godaddy_more_url_default;
    private String language;
    private String welcome_media_id;
    private String welcome_title;
    private String welcome_desc;
    private String welcome_url;
    private int isdefault;


    private List<FAQsBean> faqs;

    public String getWelcome_media_id() {
        return welcome_media_id;
    }

    public void setWelcome_media_id(String welcome_media_id) {
        this.welcome_media_id = welcome_media_id;
    }

    public String getWelcome_title() {
        return welcome_title;
    }

    public void setWelcome_title(String welcome_title) {
        this.welcome_title = welcome_title;
    }

    public String getWelcome_desc() {
        return welcome_desc;
    }

    public void setWelcome_desc(String welcome_desc) {
        this.welcome_desc = welcome_desc;
    }

    public String getCombine_faq_each_template() {
        return combine_faq_each_template;
    }

    public void setCombine_faq_each_template(String combine_faq_each_template) {
        this.combine_faq_each_template = combine_faq_each_template;
    }

    public String getCombine_faq_templates() {
        return combine_faq_templates;
    }

    public void setCombine_faq_templates(String combine_faq_templates) {
        this.combine_faq_templates = combine_faq_templates;
    }

    public String getNomatch_faq_templates() {
        return nomatch_faq_templates;
    }

    public void setNomatch_faq_templates(String nomatch_faq_templates) {
        this.nomatch_faq_templates = nomatch_faq_templates;
    }

    public int getNomatch_faq_return() {
        return nomatch_faq_return;
    }

    public void setNomatch_faq_return(int nomatch_faq_return) {
        this.nomatch_faq_return = nomatch_faq_return;
    }

    public String getGodaddy_more_url() {
        return godaddy_more_url;
    }

    public void setGodaddy_more_url(String godaddy_more_url) {
        this.godaddy_more_url = godaddy_more_url;
    }

    public String getGodaddy_more_url_default() {
        return godaddy_more_url_default;
    }

    public void setGodaddy_more_url_default(String godaddy_more_url_default) {
        this.godaddy_more_url_default = godaddy_more_url_default;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public int getIsdefault() {
        return isdefault;
    }

    public void setIsdefault(int isdefault) {
        this.isdefault = isdefault;
    }

    public List<FAQsBean> getFaqs() {
        return faqs;
    }

    public void setFaqs(List<FAQsBean> faqs) {
        this.faqs = faqs;
    }

    public String getWelcome_url() {
        return welcome_url;
    }

    public void setWelcome_url(String welcome_url) {
        this.welcome_url = welcome_url;
    }

    public static class FAQsBean {
        /**
         * name : 如何重置账户密码
         * phrase_match_return : text
         * phrase_match_keywords : ["账户密码"]
         * broad_match_keyords : ["账户","密码"]
         * title : 如何重置账户密码
         * description : 需登录 GoDaddy 网站完成两步操作，之后我们将给您发送一封附链接的电子邮件以供您重置密码使用。
         * url : https://www.gaoyongsheng.cn/faq/pages/howToResetAnAccountPassword.html
         * pic_url : https://www.gaoyongsheng.cn/downloadbuild/images/faq_godaddy_logo.png
         * text : 您可以<a href='https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxbe9a77c9f3338cb9&redirect_uri=https%3a%2f%2fwww.gaoyongsheng.cn%2foa%2fredir%2faccount%3fpath%3dsecurity%253f&response_type=code&scope=snsapi_base&state=666#wechat_redirect'>点击这里</a>前往 GoDaddy 网站的密码重置页面 -> 填写用户名和密码 -> 提交
         * <p>
         * 您还可以点击<a href='#godaddy_more_url#'>查看更多</a>了解更多问题。
         */

        private String name;
        private String phrase_match_return;
        private String title;
        private String description;
        private String url;
        private String pic_url;
        private String text;
        private List<String> phrase_match_keywords;
        private List<String> broad_match_keyords;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getPhrase_match_return() {
            return phrase_match_return;
        }

        public void setPhrase_match_return(String phrase_match_return) {
            this.phrase_match_return = phrase_match_return;
        }

        public String getTitle() {
            return title;
        }

        public void setTitle(String title) {
            this.title = title;
        }

        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }

        public String getUrl() {
            return url;
        }

        public void setUrl(String url) {
            this.url = url;
        }

        public String getPic_url() {
            return pic_url;
        }

        public void setPic_url(String pic_url) {
            this.pic_url = pic_url;
        }

        public String getText() {
            return text;
        }

        public void setText(String text) {
            this.text = text;
        }

        public List<String> getPhrase_match_keywords() {
            return phrase_match_keywords;
        }

        public void setPhrase_match_keywords(List<String> phrase_match_keywords) {
            this.phrase_match_keywords = phrase_match_keywords;
        }

        public List<String> getBroad_match_keyords() {
            return broad_match_keyords;
        }

        public void setBroad_match_keyords(List<String> broad_match_keyords) {
            this.broad_match_keyords = broad_match_keyords;
        }
    }
    //End GsonFormat.

    private static Map<String, FAQ> faqMap = new HashMap<String, FAQ>();

    public static Map<String, FAQ> getFaqMap() {
        return faqMap;
    }

    private static String defaultLang;

    private FAQ() {
    }

    public static void loadJSON() throws IOException {
        try {
            Resource resource = new ClassPathResource("templates/faq.json");
            String faq_content = FileUtil.readUTFString(resource.getInputStream());
            JsonParser jsonParser = new JsonParser();

            JsonArray faqArray = jsonParser.parseAsJsonArray(faq_content);
            for (int i = 0; i < faqArray.size(); i++) {
                JsonObject faqObj = faqArray.getJsonObject(i);
                FAQ faqLanguage = new FAQ();
                faqLanguage.setCombine_faq_each_template(faqObj.getString("combine_faq_each_template"));
                faqLanguage.setCombine_faq_templates(faqObj.getString("combine_faq_templates"));
                faqLanguage.setNomatch_faq_templates(faqObj.getString("nomatch_faq_templates"));
                faqLanguage.setNomatch_faq_return(faqObj.getInteger("nomatch_faq_return"));
                faqLanguage.setGodaddy_more_url(faqObj.getString("godaddy_more_url"));
                faqLanguage.setGodaddy_more_url_default(faqObj.getString("godaddy_more_url_default"));
                faqLanguage.setLanguage(faqObj.getString("language"));
                faqLanguage.setIsdefault(faqObj.getInteger("isdefault"));
                faqLanguage.setWelcome_media_id(faqObj.getString("welcome_media_id"));
                faqLanguage.setWelcome_title(faqObj.getString("welcome_title"));
                faqLanguage.setWelcome_desc(faqObj.getString("welcome_desc"));
                faqLanguage.setWelcome_url(faqObj.getString("welcome_url"));

                if (1 == faqLanguage.getIsdefault()) {
                    defaultLang = faqLanguage.getLanguage();
                }

                faqLanguage.setFaqs(new ArrayList<FAQsBean>());
                JsonArray faqs_array = faqObj.getJsonArray("faqs");
                for (int j = 0; j < faqs_array.size(); j++) {
                    JsonObject faq = faqs_array.getJsonObject(j);
                    FAQsBean faqBean = new FAQsBean();

                    faqBean.setName(faq.getString("name"));
                    faqBean.setTitle(faq.getString("title"));
                    faqBean.setDescription(faq.getString("description"));

                    faqBean.setPhrase_match_keywords(toStringList(faq.getJsonArray("phrase_match_keywords")));
                    faqBean.setBroad_match_keyords(toStringList(faq.getJsonArray("broad_match_keyords")));

                    faqBean.setPhrase_match_return(faq.getString("phrase_match_return"));
                    faqBean.setUrl(faq.getString("url"));
                    faqBean.setPic_url(faq.getString("pic_url"));
                    faqBean.setText(faq.getString("text"));

                    faqLanguage.faqs.add(faqBean);
                }
                faqMap.put(faqLanguage.getLanguage(), faqLanguage);
            }

            log.info(String.format("Loaded faq.json. Total loaded %s FAQs.", faqMap.size()));
        } catch (IOException e) {
            log.error("Load faq.json failed: " + e.getMessage());
            throw new IOException("Load faq.json error");
        }
    }

    public static List<FAQsBean> search(String content, String language) {
        List<FAQsBean> matchedBean = new ArrayList<FAQsBean>();
        Set<String> matchBeanNames = new HashSet<String>();

        if (StringUtils.isEmpty(content) || faqMap.containsKey(language) == false) {
            return matchedBean;
        }

        FAQ faqLanguage = faqMap.get(language);

        String content_normalized = content.trim().toLowerCase();
        //Do phrase match first
        for (FAQsBean faq : faqLanguage.getFaqs()) {
            for (String k : faq.getPhrase_match_keywords()) {
                if (content_normalized.indexOf(k) != -1) {
                    matchedBean.add(faq);
                    return matchedBean;
                }
            }
        }

        //Do broad match
        for (FAQsBean faq : faqLanguage.getFaqs()) {
            faq.getBroad_match_keyords().forEach(k -> {
                if (content_normalized.indexOf(k) != -1 && !matchBeanNames.contains(faq.getName())) {
                    matchedBean.add(faq);
                    matchBeanNames.add(faq.getName());
                }
            });
        }

        return matchedBean;
    }

    public static String getDefaultLang() {
        return defaultLang;
    }

    public static FAQ getFAQByLang(String lang) {
        return getFaqMap().get(lang);
    }

    public static List<FAQsBean> getDefaultFAQs(String language) {
        if (faqMap.containsKey(language) == false) {
            return new ArrayList<>();
        }

        return faqMap.get(language).faqs.subList(0, faqMap.get(language).getNomatch_faq_return());
    }

    private static List<String> toStringList(JsonArray array) {
        ArrayList<String> result = new ArrayList<>();
        for (int i = 0; i < array.size(); i++) {
            result.add(array.getString(i));
        }
        return result;
    }
}
